# Generated by Django 4.2.4 on 2023-09-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sci-Fi", "ScienceFiction"),
                    ("Fiction", "Fiction"),
                    ("Comedy", "Comedy"),
                ],
                default="Sci-Fi",
                max_length=20,
            ),
        ),
    ]
